name: CI Pipeline

on:
  push:
    branches:
      - main 

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Pull and run validation image
        env:
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
          STUDENT_NAME: ${{ secrets.STUDENT_NAME }}
        run: |
          docker run --rm -e STUDENT_ID=${{ secrets.STUDENT_ID }} -e STUDENT_NAME=${{ secrets.STUDENT_NAME }} registry.gitlab.com/professor-rvenson/backend-n1-validate validate

